### ISSUE TITLE
Wrong keys in dicts during the wcs creation (finalise_reduction)

### ISSUE THREAD

**Issue by oegorov** [emsellem/pymusepipe#12]
Something wrong with the keys of the dictionary defining the pixtabs for individual pointings. 
This error occurs at the stage of the creation a common wcs file (in finalise_reduction)

```
----> 4 phangs.finalise_reduction(targetname=objname, rot_pixtab=False, create_pixtables=False, create_wcs=True, create_expocubes=True, create_pointingcubes=False,
      5                       name_offset_table=offset_table)

File ~/Soft/pymusepipe/src/pymusepipe/target_sample.py:610, in MusePipeSample.finalise_reduction(self, targetname, rot_pixtab, create_wcs, create_expocubes, create_pixtables, create_pointingcubes, name_offset_table, folder_offset_table, dict_exposures, list_datasets, **kwargs)
    607     default_comb_folder = self.targets[targetname].combcubes_path
    608     folder_full_ref_wcs = kwargs.pop("folder_full_ref_wcs",
    609                                      default_comb_folder)
--> 610     self.create_reference_wcs(targetname=targetname,
    611                               folder_offset_table=folder_offset_table,
    612                               name_offset_table=name_offset_table,
    613                               dict_exposures=dict_exposures,
    614                               reference_cube=reference_cube,
    615                               refcube_name=refcube_name,
    616                               mosaic_wcs=mosaic_wcs,
    617                               pointings_wcs=pointings_wcs,
    618                               list_datasets=list_datasets,
    619                               ref_wcs=full_ref_wcs,
    620                               folder_ref_wcs=folder_full_ref_wcs,
    621                               fakemode=False)
    623 if create_expocubes:
    624     # Running the individual cubes now with the same WCS reference
    625     upipe.print_info("=========== CREATION OF EXPO CUBES =============")

File ~/Soft/pymusepipe/src/pymusepipe/target_sample.py:1097, in MusePipeSample.create_reference_wcs(self, targetname, pointings_wcs, mosaic_wcs, reference_cube, ref_wcs, refcube_name, **kwargs)
   1095 folder_ref_wcs = kwargs.pop("folder_ref_wcs", default_comb_folder)
   1096 self.init_combine(targetname=targetname, **kwargs)
-> 1097 self.pipes_combine[targetname].create_reference_wcs(pointings_wcs=pointings_wcs,
   1098                                                     mosaic_wcs=mosaic_wcs,
   1099                                                     reference_cube=reference_cube,
   1100                                                     refcube_name=refcube_name,
   1101                                                     ref_wcs=ref_wcs,
   1102                                                     folder_ref_wcs=folder_ref_wcs,
   1103                                                     **kwargs)

File ~/Soft/pymusepipe/src/pymusepipe/combine.py:762, in MusePointings.create_reference_wcs(self, pointings_wcs, mosaic_wcs, reference_cube, refcube_name, **kwargs)
    759 if refcube_name is None:
    760     upipe.print_info("@@@@@@@ First creating a reference (mosaic) "
    761                      "cube with short spectral range @@@@@@@")
--> 762     self.run_combine(lambdaminmax=lambdaminmax_for_wcs,
    763                      filter_list="white",
    764                      prefix_all=default_prefix_wcs,
    765                      targetname_asprefix=False)
    766     wcs_refcube_name = self._combined_cube_name
    767 else:

File ~/Soft/pymusepipe/src/pymusepipe/combine.py:1134, in MusePointings.run_combine(self, sof_filename, lambdaminmax, list_pointings, suffix, **kwargs)
   1130 list_pointings = self._check_list_pointings(list_pointings, self.list_pointings)
   1132 # If only 1 exposure, duplicate the pixtable
   1133 # as exp_combine needs at least 2 pixtables
-> 1134 nexpo_tocombine = sum(len(self.dict_pixtabs_in_pointings[pointing])
   1135                       for pointing in list_pointings)
   1136 if nexpo_tocombine <= 1:
   1137     upipe.print_warning("All considered pointings have a total of "
   1138                         "only one single exposure: exp_combine "
   1139                         "will not run. Please use the individual "
   1140                         "reconstructed cube.", pipe=self)

File ~/Soft/pymusepipe/src/pymusepipe/combine.py:1134, in <genexpr>(.0)
   1130 list_pointings = self._check_list_pointings(list_pointings, self.list_pointings)
   1132 # If only 1 exposure, duplicate the pixtable
   1133 # as exp_combine needs at least 2 pixtables
-> 1134 nexpo_tocombine = sum(len(self.dict_pixtabs_in_pointings[pointing])
   1135                       for pointing in list_pointings)
   1136 if nexpo_tocombine <= 1:
   1137     upipe.print_warning("All considered pointings have a total of "
   1138                         "only one single exposure: exp_combine "
   1139                         "will not run. Please use the individual "
   1140                         "reconstructed cube.", pipe=self)

KeyError: 1
```

**Comment by emsellem** [comment]
Thanks Oleg. Will look into this asap (hopefully today)

**Comment by emsellem** [comment]
Can you expose the dictionary you are providing? So I can understand. Looks like the entry "1" does not exist.

**Comment by oegorov** [comment]
Do you mean the dictionary that I use as input in MusePipeSample? Here it is 
```
dict_sample = {
   ...:         "NGC3596": ['', {1:1, 2:1, 3:1, 4:1}],
   ...: }
```

**Comment by emsellem** [comment]
No I mean the one for the exposures.

**Comment by oegorov** [comment]
Yes, it has only one entry "0", and everythin is there. Here is the content of self.dict_pixtabs_in_pointings immediatly befor the error occurs 
`{0: ['/data/beegfs/astro-storage/groups/schinnerer/PHANGS/MUSE/live/Data/Dwarfs/NGC3596/Combined/Cubes/NGC3596_PIXTABLE_REDUCED_OB001_2022-03-10T03:50:23_0001.fits', '/data/beegfs/astro-storage/groups/schinnerer/PHANGS/MUSE/live/Data/Dwarfs/NGC3596/Combined/Cubes/NGC3596_PIXTABLE_REDUCED_OB001_2022-03-10T03:50:23_0002.fits', '/data/beegfs/astro-storage/groups/schinnerer/PHANGS/MUSE/live/Data/Dwarfs/NGC3596/Combined/Cubes/NGC3596_PIXTABLE_REDUCED_OB001_2022-03-10T03:50:23_0003.fits', '/data/beegfs/astro-storage/groups/schinnerer/PHANGS/MUSE/live/Data/Dwarfs/NGC3596/Combined/Cubes/NGC3596_PIXTABLE_REDUCED_OB001_2022-03-10T03:50:23_0004.fits', '/data/beegfs/astro-storage/groups/schinnerer/PHANGS/MUSE/live/Data/Dwarfs/NGC3596/Combined/Cubes/NGC3596_PIXTABLE_REDUCED_OB002_2022-03-26T02:21:24_0001.fits', '/data/beegfs/astro-storage/groups/schinnerer/PHANGS/MUSE/live/Data/Dwarfs/NGC3596/Combined/Cubes/NGC3596_PIXTABLE_REDUCED_OB002_2022-03-26T02:21:24_0003.fits', '/data/beegfs/astro-storage/groups/schinnerer/PHANGS/MUSE/live/Data/Dwarfs/NGC3596/Combined/Cubes/NGC3596_PIXTABLE_REDUCED_OB002_2022-03-26T02:21:24_0004.fits', '/data/beegfs/astro-storage/groups/schinnerer/PHANGS/MUSE/live/Data/Dwarfs/NGC3596/Combined/Cubes/NGC3596_PIXTABLE_REDUCED_OB002_2022-03-26T02:21:24_0002.fits', '/data/beegfs/astro-storage/groups/schinnerer/PHANGS/MUSE/live/Data/Dwarfs/NGC3596/Combined/Cubes/NGC3596_PIXTABLE_REDUCED_OB003_2022-03-29T03:36:44_0002.fits', '/data/beegfs/astro-storage/groups/schinnerer/PHANGS/MUSE/live/Data/Dwarfs/NGC3596/Combined/Cubes/NGC3596_PIXTABLE_REDUCED_OB003_2022-03-29T03:36:44_0001.fits', '/data/beegfs/astro-storage/groups/schinnerer/PHANGS/MUSE/live/Data/Dwarfs/NGC3596/Combined/Cubes/NGC3596_PIXTABLE_REDUCED_OB003_2022-03-29T03:36:44_0004.fits', '/data/beegfs/astro-storage/groups/schinnerer/PHANGS/MUSE/live/Data/Dwarfs/NGC3596/Combined/Cubes/NGC3596_PIXTABLE_REDUCED_OB003_2022-03-29T03:36:44_0003.fits', '/data/beegfs/astro-storage/groups/schinnerer/PHANGS/MUSE/live/Data/Dwarfs/NGC3596/Combined/Cubes/NGC3596_PIXTABLE_REDUCED_OB004_2022-03-29T02:42:11_0003.fits', '/data/beegfs/astro-storage/groups/schinnerer/PHANGS/MUSE/live/Data/Dwarfs/NGC3596/Combined/Cubes/NGC3596_PIXTABLE_REDUCED_OB004_2022-03-29T02:42:11_0001.fits', '/data/beegfs/astro-storage/groups/schinnerer/PHANGS/MUSE/live/Data/Dwarfs/NGC3596/Combined/Cubes/NGC3596_PIXTABLE_REDUCED_OB004_2022-03-29T02:42:11_0004.fits', '/data/beegfs/astro-storage/groups/schinnerer/PHANGS/MUSE/live/Data/Dwarfs/NGC3596/Combined/Cubes/NGC3596_PIXTABLE_REDUCED_OB004_2022-03-29T02:42:11_0002.fits']}`

And this is for self.dict_pixtabs_in_datasets. This looks fine.
`{1: ['/data/beegfs/astro-storage/groups/schinnerer/PHANGS/MUSE/live/Data/Dwarfs/NGC3596/Combined/Cubes/NGC3596_PIXTABLE_REDUCED_OB001_2022-03-10T03:50:23_0001.fits', '/data/beegfs/astro-storage/groups/schinnerer/PHANGS/MUSE/live/Data/Dwarfs/NGC3596/Combined/Cubes/NGC3596_PIXTABLE_REDUCED_OB001_2022-03-10T03:50:23_0002.fits', '/data/beegfs/astro-storage/groups/schinnerer/PHANGS/MUSE/live/Data/Dwarfs/NGC3596/Combined/Cubes/NGC3596_PIXTABLE_REDUCED_OB001_2022-03-10T03:50:23_0003.fits', '/data/beegfs/astro-storage/groups/schinnerer/PHANGS/MUSE/live/Data/Dwarfs/NGC3596/Combined/Cubes/NGC3596_PIXTABLE_REDUCED_OB001_2022-03-10T03:50:23_0004.fits'], 2: ['/data/beegfs/astro-storage/groups/schinnerer/PHANGS/MUSE/live/Data/Dwarfs/NGC3596/Combined/Cubes/NGC3596_PIXTABLE_REDUCED_OB002_2022-03-26T02:21:24_0001.fits', '/data/beegfs/astro-storage/groups/schinnerer/PHANGS/MUSE/live/Data/Dwarfs/NGC3596/Combined/Cubes/NGC3596_PIXTABLE_REDUCED_OB002_2022-03-26T02:21:24_0002.fits', '/data/beegfs/astro-storage/groups/schinnerer/PHANGS/MUSE/live/Data/Dwarfs/NGC3596/Combined/Cubes/NGC3596_PIXTABLE_REDUCED_OB002_2022-03-26T02:21:24_0003.fits', '/data/beegfs/astro-storage/groups/schinnerer/PHANGS/MUSE/live/Data/Dwarfs/NGC3596/Combined/Cubes/NGC3596_PIXTABLE_REDUCED_OB002_2022-03-26T02:21:24_0004.fits'], 3: ['/data/beegfs/astro-storage/groups/schinnerer/PHANGS/MUSE/live/Data/Dwarfs/NGC3596/Combined/Cubes/NGC3596_PIXTABLE_REDUCED_OB003_2022-03-29T03:36:44_0001.fits', '/data/beegfs/astro-storage/groups/schinnerer/PHANGS/MUSE/live/Data/Dwarfs/NGC3596/Combined/Cubes/NGC3596_PIXTABLE_REDUCED_OB003_2022-03-29T03:36:44_0002.fits', '/data/beegfs/astro-storage/groups/schinnerer/PHANGS/MUSE/live/Data/Dwarfs/NGC3596/Combined/Cubes/NGC3596_PIXTABLE_REDUCED_OB003_2022-03-29T03:36:44_0003.fits', '/data/beegfs/astro-storage/groups/schinnerer/PHANGS/MUSE/live/Data/Dwarfs/NGC3596/Combined/Cubes/NGC3596_PIXTABLE_REDUCED_OB003_2022-03-29T03:36:44_0004.fits'], 4: ['/data/beegfs/astro-storage/groups/schinnerer/PHANGS/MUSE/live/Data/Dwarfs/NGC3596/Combined/Cubes/NGC3596_PIXTABLE_REDUCED_OB004_2022-03-29T02:42:11_0001.fits', '/data/beegfs/astro-storage/groups/schinnerer/PHANGS/MUSE/live/Data/Dwarfs/NGC3596/Combined/Cubes/NGC3596_PIXTABLE_REDUCED_OB004_2022-03-29T02:42:11_0002.fits', '/data/beegfs/astro-storage/groups/schinnerer/PHANGS/MUSE/live/Data/Dwarfs/NGC3596/Combined/Cubes/NGC3596_PIXTABLE_REDUCED_OB004_2022-03-29T02:42:11_0003.fits', '/data/beegfs/astro-storage/groups/schinnerer/PHANGS/MUSE/live/Data/Dwarfs/NGC3596/Combined/Cubes/NGC3596_PIXTABLE_REDUCED_OB004_2022-03-29T02:42:11_0004.fits']}`

**Comment by emsellem** [comment]
Can you please confirm the version you are using?

**Comment by oegorov** [comment]
Updated 1 hour ago from github, immediately before posting this

**Comment by emsellem** [comment]
Thanks. Will look at this. In the particular case you are showing, the two dictionary should be identical (since you have not specified explicitly the pointing association). So that's odd. Will look for the bug now.

**Comment by oegorov** [comment]
Thanks a lot! Just to let you know - I got this error with the older version (from a few days ago I think), and then reproduced it with the new version. So it is not something added with the last update

**Comment by emsellem** [comment]
Yes I think it is the interaction with the list of pixtabs which goes wrong for some reason.
When you call the function or initialise it can you try to set verbose to True (verbose=True) and reports (on Slack) what it spits out when it looks for the pixtables?

**Comment by emsellem** [comment]
Try it now? 2.17.8

**Comment by emsellem** [comment]
Seems to be solved. Let's see the next bug :-)
