### ISSUE TITLE
Initialising MusePipe with "overwrite_astropy_table=True" produces error

### ISSUE THREAD

**Issue by jusneuma** [emsellem/pymusepipe#15]
The optional keyword `overwrite_astropy_table` in `MusePipe.__init__()` produces an error in the initialisation of PipeRecipes:

`TypeError: PipeRecipes.__init__() got an unexpected keyword argument 'overwrite_astropy_table'`

Initialising MusePipe without that keyword works fine.

Is this keyword deprecated and the description of the function input parameter needs to be cleaned or is something else going wrong?

**Comment by emsellem** [comment]
It's "overwrite_astropy_tables" with an s
