### ISSUE TITLE
Feature or bug? The log files.

### ISSUE THREAD

**Issue by jusneuma** [emsellem/pymusepipe#16]
1) The log.err file contains messages that are not error messages. This seems unnecessary and confusing.

2) If errors occur in child processes the pipeline might not crash and it does not show errors in the direct shell output. Errors are only noticeable in the log.err file. Feature or bug?

**Comment by emsellem** [comment]
1- I added a test in the writing routine so that should fix it.
2- Could you give me an example? I think it's a feature as you do not necessarily want the process to crash the run for such errors. However, I could try to implement an option that catches such issues.

**Comment by jusneuma** [comment]
I think we concluded that this can be closed.
