### ISSUE TITLE
Pymusepipe doesn't find exposures during the finalise_reduction

### ISSUE THREAD

**Issue by oegorov** [emsellem/pymusepipe#17]
Hi Eric,

When I run "create_pixtables" in "finalise_reduction", I get this
`# MusePipeWarning Dataset 1 not in dictionary - skipping`

It seems that the problem is because the dictionary with individual exposures is empty - pymusepipe should (?) create it during the initialization of MusePipeSample, but this never happens.
To fix this, I do it manually: 
`from pymusepipe.combine import build_dict_exposures
dict_exposures = build_dict_exposures("/data/beegfs/astro-storage/groups/schinnerer/PHANGS/MUSE/live/Data/Dwarfs/NGC3239")`
and then add `dict_exposures` as a keyword to finalise_reduction. This works, but then I have another problem:

```
# MusePipeInfo Check file = dict_files is : {1: [('2022-01-31T05:32:58', [1, 2, 3, 4])], 2: [('2022-01-31T06:27:03', [1, 2, 3, 4])]}
# MusePipeInfo Check file = list_datasets is : [1]
# MusePipeInfo Datasets [1] - Selected 0/0 exposures after dictionary filtering
```

As result - it doesn't select anything and do nothing

**Comment by emsellem** [comment]
Ok let me have a look at this one as it is a general one. 
Two things: I can try to debug this but I will soon rely only on astropy tables to make this work. So this may become outdated.

Let's try to fix this. I'll have a look at it now.

**Comment by emsellem** [comment]
So two things. No, MusePipeSample does not create the list of exposures as it is not necessarily a time when you have everything in place. So this should actually be a default done during the final_reduction thing. Let me see...

**Comment by emsellem** [comment]
I just modified things in a major way to take this into account now using pointing_tables. It's not yet finalised but at least the first 3 steps of the finalise_reduction work assuming you provide such a pointing table. Need to think a bit more how to handle this. Will let you know as soon as it's solid.

**Comment by emsellem** [comment]
Should be solved with newer versions
