### ISSUE TITLE
Error when running run_scipost

### ISSUE THREAD

**Issue by jtmendel** [emsellem/pymusepipe#2]
I'm getting the following error when executing run_scipost as part of MusePipe:

> File "/path/pymusepipe/prep_recipes_pipe.py", line 895, in run_scipost
>     suffix, tpl, suffix_sof), new=True)
> NameError: name 'suffix_sof' is not defined

I cannot find a definition of `suffix_sof` elsewhere in the code; it looks like it may have been renamed `suffix_iexpo`, but I wanted to check if this is indeed the case before changing anything.

**Comment by emsellem** [comment]
Correct. I am doing too many changes at the same time right now as I am implementing a new feature. This is indeed suffix_iexpo. I have fixed it on my local version and will push it when I am done with the testing of the new branch. Thanks!

**Comment by emsellem** [comment]
Major rewriting have been happening. Issue is not relevant any more :-)
