### ISSUE TITLE
MusePipeSample.mosaic not using the correct input directory

### ISSUE THREAD

**Issue by cloud182** [emsellem/pymusepipe#20]
Hi Eric,

I am reporting a bug in the code that I found while trying to mosaic NGC253 data. MusePipeSample.mosaic has the possibility to add a folder for the input datacubes via the keyword "folder_cubes". However, this variable is not given as input for .init_mosaic. Therefore the code will create the mosaic always starting from the default location. This is a problem when trying to mosaic cubes that were move under different folders.

Cheers,
Enrico

**Comment by emsellem** [comment]
Fixed in new version 2.25.2 Thanks Enrico!
